# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'cmmnd1' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for cmmnd1

  target 'cmmnd1-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'cmmnd1Tests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'cmmnd1-tvOS' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for cmmnd1-tvOS

#  target 'cmmnd1-tvOSTests' do
#    inherit! :search_paths
    # Pods for testing
#  end

end
